name: run_api_automation

on:
   # push:
    # branches: [ master, feature1 ]
  schedule:
    - cron: "0 */2 * * *"

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: python -m pip install --upgrade pip   

      - name: install requirments.txt  #         run: pytest_api\pytest_venv\Scripts\activate.bat
        run: pip3 install -r pytest_api/requirements.txt
        
      - name: Run automation tests
        working-directory: ./pytest_api
     
        run: |
           pytest_venv\Scripts\activate.bat
           pytest --html=.\reports\report.html --self-contained-html


